using System.Resources;

namespace TouchMappingAgent.WPF.Localization;

/// <summary>
/// Access point for the UI resource files.
///
/// Written by hand rather than generated by the resx designer. The designer emits one property
/// per key, which is of no use here: the keys that matter most arrive at runtime from the service
/// as <see cref="Shared.Localization.LocalizableText"/> and can only be looked up by string. A
/// generated file would also have to be regenerated on every key added by the translation pass,
/// which is exactly the churn this class avoids.
/// </summary>
internal static class Strings
{
    /// <summary>
    /// The resource manager over Strings.resx (German, neutral) and its satellites.
    /// </summary>
    public static ResourceManager ResourceManager { get; } = new(
        "TouchMappingAgent.WPF.Localization.Strings",
        typeof(Strings).Assembly);
}
